### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by K4SPERSKY9655**
[+] Improved The Installation Tab

### CODE REVIEW

**Comment by K4SPERSKY9655** [comment]
i'm trying to make the Instalacion tab look better

**Comment by K4SPERSKY9655** [comment]
> [+] Installation Tutorials improved

[+] Improved The Installation tab

**Comment by ALittlePatate** [comment]
seems fine to me

**Comment by K4SPERSKY9655** [comment]
thx

**Pull request merged**
